In [20]:
from csv import reader

#Nessa classe foram juntadas várias funções da solução original do problema do dataquest
class Dataset():
    def __init__(self, arquivo_csv):
        opened_file = open(arquivo_csv, encoding="utf8")
        read_file = reader(opened_file)
        
        dataset = list(read_file)
        header = dataset[0]
        dataset = dataset[1:]
        
        self.header = header
        self.dataset = dataset

    def explore_data(self,start, end, rows_and_columns=False):
        dataset_slice = self.dataset[start:end]    
        for row in dataset_slice:
          print(row)
          print('\n') # adds a new (empty) line between rows

        if rows_and_columns:
          print('Number of rows:', len(self.dataset))
          print('Number of columns:', len(self.dataset[0])) 

    def delete_line(self,line):
        del self.dataset[line]
    
    def duplicate_items(self, p_header, duplicate=True):
        duplicate_lines = []
        unique_lines = []
        for line in self.dataset:
          item = line[p_header]
          if item in unique_lines:
            duplicate_lines.append(item)
          else:
            unique_lines.append(item)

        print("Number of duplicate:", (len(duplicate_lines) if duplicate else unique_lines))

    def is_english(string):
      non_ascii = 0

      for character in string:
          if ord(character) > 127:
              non_ascii += 1
      return False if  non_ascii > 3 else True

    def no_english_items(self , parameter):
        no_english_list = []
        for line in self.dataset:
          if Dataset.is_english(line[parameter]) == False:
            no_english_list.append(line[parameter])
        print("Number of no English Items: ", len(no_english_list))

    def clean_no_english_items(self,parameter):
        no_english_list = []
        for line in self.dataset:
          if Dataset.is_english(line[parameter]) == False:
            Dataset.delete_line(self,self.dataset.index(line))
        return self.dataset

    def only_free(self, column):
        dataset_free = []
        for app in self.dataset:
          price = app[column]
          if price == '0' or price == '0.0':
            dataset_free.append(app)
        self.dataset = dataset_free

    def freq_table(self, index):
        table = {}
        total = 0
        for row in self.dataset:
            total += 1
            value = row[index]
            if value in table:
                table[value] += 1
            else:
                table[value] = 1
        
        table_percentages = {}
        
        for key in table:
            percentage = (table[key] / total) * 100
            table_percentages[key] = percentage 
    
        return table_percentages


    def display_table(self, index):
        table = Dataset.freq_table(self, index)
        table_display = []
        for key in table:
            key_val_as_tuple = (table[key], key)
            table_display.append(key_val_as_tuple)
        
        table_sorted = sorted(table_display, reverse = True)
        for entry in table_sorted:
            print(entry[1], ':', entry[0])
          

# Instâncias da classe Dataset passando como parâmetros os arquivos .csv dos apps de cada loja de aplicativos

In [21]:
ios_apps_dataset = Dataset('googleplaystore.csv')
android_apps_dataset = Dataset('AppleStore.csv')

# Exemplos de uso da Classe Dataset:

- Printando os cabeçalhos das planilhas

In [22]:
print(android_apps_dataset.header) #printa apenas os cabeçalhos da planilha de apps da google play
print(ios_apps_dataset.header) #printa apenas os cabeçalhos da planilha de apps da apple store

['', 'id', 'track_name', 'size_bytes', 'currency', 'price', 'rating_count_tot', 'rating_count_ver', 'user_rating', 'user_rating_ver', 'ver', 'cont_rating', 'prime_genre', 'sup_devices.num', 'ipadSc_urls.num', 'lang.num', 'vpp_lic']
['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type', 'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver']


Ao rodar o código acima, o resultado deve ser este:

```
['', 'id', 'track_name', 'size_bytes', 'currency', 'price', 'rating_count_tot', 'rating_count_ver', 'user_rating', 'user_rating_ver', 'ver', 'cont_rating', 'prime_genre', 'sup_devices.num', 'ipadSc_urls.num', 'lang.num', 'vpp_lic']

['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type', 'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver', 'Android Ver']
```

- "Explorando" o dataset do android (iremos percorrer desde o cabeçalho até a linha 3 da planilha dos apps do android)

In [25]:
android_apps_dataset.explore_data(0, 3, True)

['1', '281656475', 'PAC-MAN Premium', '100788224', 'USD', '3.99', '21292', '26', '4', '4.5', '6.3.5', '4+', 'Games', '38', '5', '10', '1']


['2', '281796108', 'Evernote - stay organized', '158578688', 'USD', '0', '161065', '26', '4', '3.5', '8.2.2', '4+', 'Productivity', '37', '5', '23', '1']


['3', '281940292', 'WeatherBug - Local Weather, Radar, Maps, Alerts', '100524032', 'USD', '0', '188583', '2822', '3.5', '4.5', '5.0.0', '4+', 'Weather', '37', '5', '3', '1']


Number of rows: 7197
Number of columns: 17


---
Ao executar o código acima, o resultado esperado é este:

```
['1', '281656475', 'PAC-MAN Premium', '100788224', 'USD', '3.99', '21292', '26', '4', '4.5', '6.3.5', '4+', 'Games', '38', '5', '10', '1']


['2', '281796108', 'Evernote - stay organized', '158578688', 'USD', '0', '161065', '26', '4', '3.5', '8.2.2', '4+', 'Productivity', '37', '5', '23', '1']


['3', '281940292', 'WeatherBug - Local Weather, Radar, Maps, Alerts', '100524032', 'USD', '0', '188583', '2822', '3.5', '4.5', '5.0.0', '4+', 'Weather', '37', '5', '3', '1']


Number of rows: 7197
Number of columns: 17
```

- Pode-se utilizar os diversos outros métodos dessa classe normalmente. Estes foram apenas alguns exemplos.